/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia sesión del empleador (respaldado por Auth.js). */
        post: operations["iniciarSesionEmpleador"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cierra la sesión del empleador. */
        post: operations["cerrarSesionEmpleador"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve la sesión actual del empleador. */
        get: operations["obtenerSesion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acceso/enlace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Genera (o regenera) el enlace de acceso de solo lectura de la empleada. */
        post: operations["generarEnlaceAcceso"];
        /** Revoca el enlace de acceso actual de la empleada. */
        delete: operations["revocarEnlaceAcceso"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/acceso/validar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Valida el token de la empleada y devuelve su contexto de consulta. */
        get: operations["validarAccesoEmpleada"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/empleada": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve la ficha de la empleada (incluye fecha de cumpleaños). */
        get: operations["obtenerEmpleada"];
        /** Crea/actualiza la ficha y las fechas de contrato de la empleada. */
        put: operations["actualizarEmpleada"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configuracion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve salario base y días laborales. */
        get: operations["obtenerConfiguracion"];
        /** Actualiza salario base y/o días laborales. */
        put: operations["actualizarConfiguracion"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items-adicionales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista los items de pago adicional configurados. */
        get: operations["listarItemsAdicionales"];
        put?: never;
        /** Crea un item de pago adicional. */
        post: operations["crearItemAdicional"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items-adicionales/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualiza un item de pago adicional. */
        put: operations["actualizarItemAdicional"];
        post?: never;
        /** Elimina un item de pago adicional. */
        delete: operations["eliminarItemAdicional"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/liquidaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial de liquidaciones (meses) registradas. */
        get: operations["listarLiquidaciones"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/liquidaciones/{anio}/{mes}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anio: number;
                mes: number;
            };
            cookie?: never;
        };
        /** Obtiene (o inicializa el borrador de) la liquidación de un mes, con desglose y calendario. */
        get: operations["obtenerLiquidacion"];
        /** Actualiza las novedades del borrador (inasistencias, items, montos puntuales, notas). */
        put: operations["actualizarLiquidacion"];
        post?: never;
        /** Elimina la liquidación de un mes del historial. */
        delete: operations["eliminarLiquidacion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/liquidaciones/{anio}/{mes}/cierre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aplica/cierra la liquidación; congela salario, valores de items y días laborales. */
        post: operations["cerrarLiquidacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/liquidaciones/{anio}/{mes}/reapertura": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reabre una liquidación cerrada para corregirla (vuelve a BORRADOR). */
        post: operations["reabrirLiquidacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve la configuración del menú y las entradas de la plantilla. */
        get: operations["obtenerMenu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu/configuracion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Configura las comidas a incluir y la periodicidad del menú. */
        put: operations["actualizarConfiguracionMenu"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu/entradas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Define/actualiza las entradas de la plantilla del menú (por semana, día y comida). */
        put: operations["actualizarMenu"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tareas/rutina": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve la rutina de tareas por día de la semana. */
        get: operations["obtenerRutinaTareas"];
        /** Define/actualiza la rutina de tareas (checklist por día con horarios opcionales). */
        put: operations["actualizarRutinaTareas"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tareas/dia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checklist de tareas de una fecha, con su estado de cumplimiento. */
        get: operations["obtenerTareasDelDia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tareas/cumplimiento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Marca una tarea como hecha/pendiente en una fecha (permitido a la empleada). */
        put: operations["marcarTarea"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tareas/historico": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Histórico de cumplimiento de tareas por fecha (rango). */
        get: operations["obtenerHistoricoTareas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Código de negocio estable. Ej: LIQUIDACION_CERRADA, INASISTENCIA_INVALIDA, MES_FUERA_DE_CONTRATO, MES_DUPLICADO, ACCESO_INVALIDO, NO_AUTORIZADO. */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        DiaSemana: "LUNES" | "MARTES" | "MIERCOLES" | "JUEVES" | "VIERNES" | "SABADO" | "DOMINGO";
        /** @enum {string} */
        EstadoLiquidacion: "BORRADOR" | "CERRADA";
        /** @enum {string} */
        Periodicidad: "SEMANAL" | "QUINCENAL" | "MENSUAL";
        /** @enum {string} */
        TipoDiaCalendario: "TRABAJADO" | "INASISTENCIA" | "FESTIVO" | "NO_LABORAL" | "FUERA_CONTRATO";
        EnlaceAcceso: {
            token: string;
            /** @description Enlace completo para compartir con la empleada. */
            url: string;
            activo: boolean;
        };
        ContextoEmpleada: {
            nombre: string;
            valido: boolean;
        };
        Empleada: {
            nombre: string;
            /** Format: date */
            fechaNacimiento: string;
            /** Format: date */
            fechaInicioContrato: string;
            /** Format: date */
            fechaFinContrato?: string | null;
        };
        Configuracion: {
            /** @description COP entero. Default 700000. */
            salarioBase: number;
            diasLaborales: components["schemas"]["DiaSemana"][];
        };
        ItemAdicional: {
            id: string;
            nombre: string;
            /** @description COP entero. */
            valorUnitario: number;
            color?: string | null;
            activo: boolean;
        };
        ItemAdicionalInput: {
            nombre: string;
            valorUnitario: number;
            color?: string | null;
            /** @default true */
            activo: boolean;
        };
        LiquidacionResumen: {
            anio: number;
            mes: number;
            estado: components["schemas"]["EstadoLiquidacion"];
            /** @description COP entero. */
            total: number;
        };
        Desglose: {
            /** @description Días laborales del mes completo (denominador). */
            diasLaboralesMes: number;
            /** @description Festivos L–S del mes, pagados, no descontados. */
            festivosEnDiaLaboral: number;
            /** @description Días efectivamente trabajados (dentro de contrato, menos inasistencias). */
            diasTrabajados: number;
            valorDia: number;
            subtotalDias: number;
            subtotalItems: number;
            subtotalMontosPuntuales: number;
            total: number;
        };
        DiaCalendario: {
            /** Format: date */
            fecha: string;
            tipo: components["schemas"]["TipoDiaCalendario"];
            /** @description Ids de items adicionales asociados a ese día (si aplica, para color). */
            itemsAdicionales?: string[];
        };
        LiquidacionItem: {
            itemId: string;
            nombre: string;
            /** @description Valor congelado en la liquidación. */
            valorUnitario: number;
            cantidad: number;
            subtotal: number;
        };
        MontoPuntual: {
            id?: string;
            descripcion: string;
            /** @description COP entero. */
            monto: number;
        };
        Liquidacion: {
            anio: number;
            mes: number;
            estado: components["schemas"]["EstadoLiquidacion"];
            desglose: components["schemas"]["Desglose"];
            calendario: components["schemas"]["DiaCalendario"][];
            inasistencias: string[];
            items: components["schemas"]["LiquidacionItem"][];
            montosPuntuales: components["schemas"]["MontoPuntual"][];
            /** @description Privada del empleador. NUNCA presente en respuestas al rol empleada (RN-12). */
            notas?: string | null;
        };
        /** @description Edición del borrador del mes (novedades). Falla si la liquidación está CERRADA. */
        ActualizarLiquidacionInput: {
            inasistencias?: string[];
            items?: {
                itemId: string;
                cantidad: number;
            }[];
            montosPuntuales?: {
                descripcion: string;
                monto: number;
            }[];
            notas?: string | null;
        };
        MenuConfig: {
            /** @description Comidas configurables, ej. ['Desayuno','Almuerzo','Cena']. */
            comidas: string[];
            periodicidad: components["schemas"]["Periodicidad"];
        };
        MenuEntrada: {
            /** @description Índice de semana del ciclo (0 = semana 1). */
            semana: number;
            diaSemana: components["schemas"]["DiaSemana"];
            comida: string;
            descripcion: string;
        };
        Menu: {
            configuracion: components["schemas"]["MenuConfig"];
            entradas: components["schemas"]["MenuEntrada"][];
        };
        RutinaTarea: {
            id: string;
            diaSemana: components["schemas"]["DiaSemana"];
            descripcion: string;
            /** @description HH:mm, opcional. */
            horaInicio?: string | null;
            /** @description HH:mm, opcional. */
            horaFin?: string | null;
            orden: number;
        };
        RutinaTareaInput: {
            diaSemana: components["schemas"]["DiaSemana"];
            descripcion: string;
            horaInicio?: string | null;
            horaFin?: string | null;
            orden: number;
        };
        TareaDelDia: {
            rutinaTareaId: string;
            descripcion: string;
            horaInicio?: string | null;
            horaFin?: string | null;
            hecha: boolean;
        };
        MarcarTareaInput: {
            /** Format: date */
            fecha: string;
            rutinaTareaId: string;
            hecha: boolean;
        };
        CumplimientoTarea: {
            /** Format: date */
            fecha: string;
            rutinaTareaId: string;
            descripcion: string;
            hecha: boolean;
        };
    };
    responses: {
        /** @description Datos inválidos. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No autenticado. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No autorizado para el rol. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Recurso no encontrado. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicto de estado (ej. liquidación cerrada, mes duplicado). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    iniciarSesionEmpleador: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Sesión iniciada (cookie establecida). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    cerrarSesionEmpleador: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión cerrada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    obtenerSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión vigente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        autenticado: boolean;
                        email?: string | null;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    generarEnlaceAcceso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enlace vigente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnlaceAcceso"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revocarEnlaceAcceso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enlace revocado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    validarAccesoEmpleada: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token válido. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextoEmpleada"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    obtenerEmpleada: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ficha de la empleada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Empleada"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    actualizarEmpleada: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Empleada"];
            };
        };
        responses: {
            /** @description Ficha actualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Empleada"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["BadRequest"];
        };
    };
    obtenerConfiguracion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuración vigente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Configuracion"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    actualizarConfiguracion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Configuracion"];
            };
        };
        responses: {
            /** @description Configuración actualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Configuracion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["BadRequest"];
        };
    };
    listarItemsAdicionales: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de items. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemAdicional"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    crearItemAdicional: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemAdicionalInput"];
            };
        };
        responses: {
            /** @description Item creado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemAdicional"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["BadRequest"];
        };
    };
    actualizarItemAdicional: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemAdicionalInput"];
            };
        };
        responses: {
            /** @description Item actualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemAdicional"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["BadRequest"];
        };
    };
    eliminarItemAdicional: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item eliminado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listarLiquidaciones: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Historial. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiquidacionResumen"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    obtenerLiquidacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anio: number;
                mes: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liquidación del mes. Para el rol empleada, `notas` se omite (RN-12). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liquidacion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Mes completamente fuera del periodo de contrato (no liquidable). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    actualizarLiquidacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anio: number;
                mes: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarLiquidacionInput"];
            };
        };
        responses: {
            /** @description Liquidación recalculada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liquidacion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description La liquidación está CERRADA o una inasistencia es inválida (festivo/no laboral/fuera de contrato). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["BadRequest"];
        };
    };
    eliminarLiquidacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anio: number;
                mes: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liquidación eliminada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cerrarLiquidacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anio: number;
                mes: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liquidación cerrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liquidacion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description La liquidación ya está cerrada. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    reabrirLiquidacion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anio: number;
                mes: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liquidación reabierta. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liquidacion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description La liquidación ya estaba en borrador. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    obtenerMenu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Menú vigente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Menu"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    actualizarConfiguracionMenu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuConfig"];
            };
        };
        responses: {
            /** @description Configuración del menú actualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuConfig"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["BadRequest"];
        };
    };
    actualizarMenu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuEntrada"][];
            };
        };
        responses: {
            /** @description Entradas del menú actualizadas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuEntrada"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["BadRequest"];
        };
    };
    obtenerRutinaTareas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rutina de tareas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RutinaTarea"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    actualizarRutinaTareas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RutinaTareaInput"][];
            };
        };
        responses: {
            /** @description Rutina actualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RutinaTarea"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["BadRequest"];
        };
    };
    obtenerTareasDelDia: {
        parameters: {
            query: {
                fecha: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tareas del día. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TareaDelDia"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    marcarTarea: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarcarTareaInput"];
            };
        };
        responses: {
            /** @description Estado de la tarea actualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CumplimientoTarea"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["BadRequest"];
        };
    };
    obtenerHistoricoTareas: {
        parameters: {
            query: {
                desde: string;
                hasta: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cumplimientos en el rango. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CumplimientoTarea"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
